config_version = 12

[bar.default]
center = [ "clock", "weather" ]
concave_edge_corners = false
end = [ "tray", "notifications", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
margin_edge = 6
margin_ends = 6
padding = 4
radius = 16
shadow = false
start = [ "launcher", "taskbar" ]
thickness = 40

[control_center]
sidebar = "none"
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "power_profile"

[location]
address = "Wuhan,China"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 128.0
    box_width = 720.0
    cx = 914.5
    cy = 649.5
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 0.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 8.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 208.0
    box_width = 304.0
    cx = 914.5
    cy = 475.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        color = "on_secondary"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 176.0
    box_width = 192.0
    cx = 114.5
    cy = 1043.5
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        color = "on_secondary"
        shadow = false
        show_forecast = true

[osd]
position = "top_right"
position_vertical = "top_right"

[shell]
app_icon_color = "primary"
avatar_path = "/home/ordchaos/Pictures/avatar.png"
font_family = "Segoe UI"
settings_show_advanced = false

    [shell.launcher]
    sort_by_usage = false

    [shell.panel]
    open_near_click_control_center = true

    [shell.screenshot]
    directory = "/home/ordchaos/Pictures/Screenshots"

[system.monitor]
enabled = false

[theme]
builtin = "Nord"
community_palette = "One"
custom_palette = "fluent-blue"
mode = "light"
source = "custom"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt", "starship" ]
    community_ids = [ "obsidian", "vscode", "discord", "obs", "steam", "telegram" ]

[wallpaper.default]
path = "/home/ordchaos/Pictures/Wallpapers/golden-gate-bridge-fog.jpg"

[wallpaper.last]
path = "/home/ordchaos/Pictures/Wallpapers/golden-gate-bridge-fog.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/ordchaos/Pictures/Wallpapers/golden-gate-bridge-fog.jpg"

[[wallpaper.favorite]]
builtin_palette = "Ayu"
palette_source = "builtin"
path = "/home/ordchaos/Pictures/Wallpapers/BanYue.jpeg"
theme_mode = "light"

[widget.battery]
capsule = true

[widget.bluetooth]
capsule = true

[widget.brightness]
capsule = true

[widget.control-center]
capsule = true

[widget.launcher]
capsule = true

[widget.network]
capsule = true
show_label = false

[widget.notifications]
capsule = true

[widget.session]
capsule = true

[widget.taskbar]
group_by_workspace = true
show_all_outputs = true

[widget.tray]
capsule = true
drawer = true
drawer_columns = 5
match_adjacent_spacing = true
pinned = [ "fcitx5" ]

[widget.volume]
capsule = true