;;; System-owned resolv.conf bootstrap：无状态根上的 DNS 启动修复。
;;;
;;; 背景（2026-08 实测 + pinned Guix df854574 / store artifact 审计）：
;;;   NetworkManager 1.54.3 以 -Dconfig_dns_rc_manager_default=resolvconf
;;;   编译（gnu/packages/gnome.scm），DNS 更新经 openresolv 3.17.4 的
;;;   resolvconf 落盘；openresolv 3.17 起 libc subscriber 要求已有
;;;   /etc/resolv.conf 首行必须是其 ownership signature
;;;   "# Generated by resolvconf"，否则拒绝写入（signature mismatch，
;;;   exit 1）；Guix nscd-activation（gnu/services/base.scm）在文件
;;;   不存在时创建普通文件 "# This is a placeholder."（无签名）；
;;;   无状态根每 boot 重建 /etc → placeholder 每 boot 复现 → NM 的
;;;   resolvconf -a 每 boot 被拒 → DNS 每 boot 断。
;;;
;;; 修复：system activation 之后、NetworkManager 之前，用 openresolv
;;;   官方 -u（update）接口接管。store artifact 实测语义
;;;   （openresolv-3.17.4/lib/resolvconf/libc）：CMD=u 对首行非签名
;;;   的文件先备份到 resolv.conf.bak 再覆盖（官方 takeover path——
;;;   libc 拒绝 -a 时的报错原文就是 "run `resolvconf -u` to update"）。
;;;   不使用 -I：它是 state dir init（清 /run/resolvconf 的残留
;;;   record），在本系统每 boot 全新的 /run 上无清理对象，且 -I 经
;;;   libc subscriber 时对非签名文件同样拒绝（不能用于接管）。
;;;
;;; 行为边界：
;;;   - 只在 /etc/resolv.conf【缺失】或内容【精确等于】Guix nscd
;;;     placeholder 时执行 -u；symlink / 用户自定义普通文件 / 其它
;;;     resolver manager 的文件 / 已由 openresolv 管理的文件一律不动；
;;;   - 不持久化任何 DNS runtime 数据；/run/resolvconf 每 boot 由
;;;     resolvconf 自身按需创建（--rundir=/run 编译期固定）；
;;;   - 不解析 DHCP、不构造 nameserver、不硬编码 DNS server——
;;;     nameserver 始终由 NetworkManager 的 resolvconf -a 提供；
;;;   - /etc/resolv.conf 保持为运行时生成物（openresolv 是 owner）；
;;;     仓库未来可经 etc-service 声明式分发 /etc/resolvconf.conf
;;;     作为 DNS policy/config source（openresolv 的 SYSCONFDIR 默认
;;;     读取 /etc/resolvconf.conf；注意一旦提供该文件，named/dnsmasq/
;;;     unbound 等 subscriber 会随之激活，配置需按需显式关闭）。
;;;
;;; one-shot 的重复执行安全：-u 对已带签名的文件幂等（libc 的内容
;;; 相等检查提前退出）；对非签名文件会备份到 .bak 后覆盖（不删除
;;; 用户数据）。

(define-module (guixcfg system resolvconf)
               #:use-module (gnu services)          ; simple-service
               #:use-module (gnu services shepherd) ; shepherd-service
               #:use-module (gnu packages dns)      ; openresolv
               #:use-module (guix gexp)
               #:use-module (guix modules)          ; source-module-closure
               #:export (%guix-nscd-placeholder-content
                         resolvconf-bootstrap-program
                         resolvconf-bootstrap-service))

;; Guix nscd-activation（gnu/services/base.scm，pinned）创建的占位
;; 内容（display "# This is a placeholder.\n"）——唯一允许被本服务
;; 接管的"非 openresolv 所有"文件形态。
(define %guix-nscd-placeholder-content "# This is a placeholder.\n")

(define (resolvconf-bootstrap-program)
  "生成 resolvconf-bootstrap 程序：当 /etc/resolv.conf 缺失、或内容
精确等于 Guix nscd placeholder 时，调用 openresolv 官方 -u 接管；
其余形态（symlink / 用户文件 / 其它 manager / 已管理文件）不触碰，
退出码 0（no-op）。resolvconf 二进制取 store 内锁定版 openresolv
（file-append），不依赖 PATH。"
  (program-file
   "resolvconf-bootstrap"
   (with-imported-modules
    (source-module-closure '((guix build utils)
                             (ice-9 rdelim)))
    #~(begin
       (use-modules (guix build utils)
                    (ice-9 rdelim))
       (define resolv-conf "/etc/resolv.conf")
       (define (nscd-placeholder-or-absent?)
         "RESOLV-CONF 缺失、或为常规文件且内容精确等于 Guix nscd
placeholder 时返回 #t（lstat 报 ENOENT 即缺失——dangling symlink
除外：lstat 本身成功、type 为 symlink，落入 #f 分支不接管）。"
         (catch 'system-error
           (lambda ()
             (let ((st (lstat resolv-conf)))
               (and (eq? (stat:type st) 'regular)
                    (call-with-input-file resolv-conf
                      (lambda (port)
                        (string=? (read-string port)
                                  #$%guix-nscd-placeholder-content))))))
           (lambda args
             #t)))
       (when (nscd-placeholder-or-absent?)
         (invoke #$(file-append openresolv "/sbin/resolvconf") "-u"))))))

(define (resolvconf-bootstrap-service)
  "one-shot shepherd 服务：NetworkManager 之前执行 bootstrap program。
requirement 为空——system activation 先于 shepherd 运行（/etc 已
物化），先后约束由 NetworkManager 侧对本服务的 requirement 反向
锚定（host assembly 声明；见 (guixcfg hosts vm)）。"
  (simple-service 'resolvconf-bootstrap shepherd-root-service-type
                  (list (shepherd-service
                         (provision '(resolvconf-bootstrap))
                         (requirement '())
                         (one-shot? #t)
                         (respawn? #f)
                         (documentation
                          "Take over /etc/resolv.conf ownership via \
openresolv -u before NetworkManager starts (acts only on the exact \
Guix nscd placeholder or a missing file; never touches symlinks, user \
files or already-managed files).")
                         (start #~(lambda ()
                                    (zero? (system*
                                            #$(resolvconf-bootstrap-program)))))
                         (stop #~(const #f))))))
